version: '3.8'
services:
# app:
#    build: .
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=production
#      - GEMINI_API_KEY=${GEMINI_API_KEY}
#    volumes:
#      - .:/app
#      - /app/node_modules
#    depends_on:
#      - db
#
  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: prisma-docker-db